server {
    listen 3006;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback — toutes les routes React → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy → APK Scanner
    location /api/apk-scanner/ {
        proxy_pass http://apk-scanner:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 200m;
        proxy_read_timeout 300s;
    }

    # Proxy → Secret Hunter
    location /api/secret-hunter/ {
        proxy_pass http://secret-hunter:5002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → Network Inspector
    location /api/network-inspector/ {
        proxy_pass http://network-inspector:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → Crypto Check
    location /api/crypto-check/ {
        proxy_pass http://crypto-check:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → FixSuggest
    location /api/fix-suggest/ {
        proxy_pass http://fixsuggest:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → ReportGen
    location /api/reportgen/ {
        proxy_pass http://reportgen:3005/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → ML Model
    location /api/ml-model/ {
        proxy_pass http://ml-model:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy → CI Connector / API Gateway
    location /api/ {
        proxy_pass http://ci-connector:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 200m;
    }

    gzip on;
    gzip_types text/plain application/javascript application/json text/css image/svg+xml;
}
